require("config.options")
require("config.keymaps")

require("plugins.lazy")
require("config.color-scheme")
require("plugins.dashboard-nvim")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.lualine")
require("plugins.mason")
require("plugins.mason-lspconfig")
require("plugins.nvim-cmp")
require("plugins.lspconfig")
require("plugins.lspsaga")
require("plugins.treesitter")
require("plugins.formatter")